### ISSUE TITLE
Does not work in melodic（Python2） environment　[branch:melodic]

### ISSUE THREAD

**Issue by shuto1441** [shuto1441/orientalmotor_ros#2]
On the melodic branch
if following command is done,
`rosrun orientalmotor_ros serial_node.py`
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1550, in __call__
    return self.func(*args)
  File "/home/ishii/catkin_ws/src/orientalmotor_ros/src/orientalmotor_ros/MotorReconfigure.py", line 22, in <lambda>
    button1 = tk.Button(self.master, text="positiong rotate", command=lambda: self.positioning_rotate(motor))
  File "/home/ishii/catkin_ws/src/orientalmotor_ros/src/orientalmotor_ros/MotorReconfigure.py", line 46, in positioning_rotate
    self.apply_angle(msg)
  File "/home/ishii/catkin_ws/src/orientalmotor_ros/src/orientalmotor_ros/MotorReconfigure.py", line 141, in apply_angle
    command += self.error_check(command)
  File "/home/ishii/catkin_ws/src/orientalmotor_ros/src/orientalmotor_ros/MotorReconfigure.py", line 82, in error_check
    crc_register ^= data_byte
TypeError: unsupported operand type(s) for ^=: 'int' and 'str'
```

error_check function is created based on the format of crc16 modbus↓
[https://qiita.com/ymsk_sky/items/7e6f20b37101805594b4](url)

Since python2 does not have a byte type, I do not know how to write the XOR part.

**Comment by tongtybj** [comment]
A compatible solution for both python2&3 that I found is to use `bytearray`:

https://github.com/shuto1441/orientalmotor_ros/blob/melodic/src/orientalmotor_ros/MotorReconfigure.py#L81
can be modified to: 
```
 for data_byte in bytearray(query):
```

Could I have a try, and tell me the result.

**Comment by shuto1441** [comment]
Thank you!
After fixing it, I was able to confirm that it works.
